"""refresh token model

Revision ID: 654bbf43c41d
Revises: 9506102603d2
Create Date: 2025-07-23 14:34:24.293283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654bbf43c41d'
down_revision = '9506102603d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token_type')
    # ### end Alembic commands ###
